### ISSUE TITLE
I18n.

### ISSUE THREAD

**Issue by olegispe** [traa-pixelcanvas/TraanvasBot#51] opened 2019-04-18 18:44 UTC
Remove the Turkish translations (if not in use) seeing as none of us are Turkish as far as I'm aware, and only include/add translations for languages that we need.

Also, the ability to set locale when running the script would be nice for people whose preferred language isn't the same as their locale's language.

**Comment by aud-tree** [comment] 2019-04-18 18:56
duplicate of #47

**Closed by aud-tree** 2019-04-18 18:56 UTC
Labels: duplicate
